# Enable builds on all branches
trigger:
  batch: false
  branches:
    include:
      - '*'

# Enable PR triggers that target the master branch
pr:
  autoCancel: true # cancel previous builds on push
  branches:
    include:
      - master

jobs:
  - job: main
    timeoutInMinutes: 360
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - bash: |
          sudo mkdir -p /nix
          sudo chown "$(id -u):$(id -g)" /nix
          curl -sfL https://nixos.org/nix/install | bash
        displayName: Installing Nix
