{-# LANGUAGE ForeignFunctionInterface #-}

-- | Fused per-layer kernel that calls polyhedrally-generated matvec kernels.
--
-- Two OMP parallel regions per layer (attn + FFN). Each region calls
-- the compiled polyhedral matvec via function pointers. The matvec
-- kernels use nested OMP (omp for inside the existing parallel region).
module Isl.Infer.Kernel.FusedLayer
  ( CompiledLayer(..)
  , compileLayer
  ) where

import Data.Int (Int64)
import Data.Word (Word8)
import Foreign.Ptr (Ptr, FunPtr, castFunPtr)

import Isl.Infer.Model (LlamaConfig(..))
import Isl.Infer.Runtime

-- | The fused layer function takes all buffers, weights, and FUNCTION POINTERS
-- to the polyhedral matvec kernels. This way the fused layer is a thin
-- scheduling shell and the actual matvec is polyhedrally generated.
type LayerFnC
  =  Ptr Float -> Ptr Float -> Ptr Float       -- x, xb, xb2
  -> Ptr Float -> Ptr Float -> Ptr Float       -- q, k, v
  -> Ptr Float -> Ptr Float                     -- hb, hb2
  -> Ptr Float -> Ptr Float                     -- attn_out, scores
  -> Ptr Float -> Ptr Float                     -- k_cache, v_cache
  -> Ptr Word8 -> Ptr Word8 -> Ptr Word8 -> Ptr Word8  -- wq, wk, wv, wo
  -> Ptr Word8 -> Ptr Word8 -> Ptr Word8               -- w_gate, w_up, w_down
  -> Ptr Float -> Ptr Float                     -- attn_norm, ffn_norm
  -> Ptr Float                                  -- inv_freq
  -> Int64                                      -- pos
  -> IO ()

foreign import ccall "dynamic"
  mkLayerFn :: FunPtr LayerFnC -> LayerFnC

data CompiledLayer = CompiledLayer
  { clFn     :: !LayerFnC
  , clKernel :: !CompiledKernel
  , clSource :: !String
  }

compileLayer :: LlamaConfig -> IO CompiledLayer
compileLayer cfg = do
  let src = genLayer cfg
  ck <- compileAndLoad "fused_layer" src
  let fn = mkLayerFn (castFunPtr (ckFuncPtr ck))
  return CompiledLayer { clFn = fn, clKernel = ck, clSource = src }

-- | Generate the fused layer.
-- Two OMP parallel regions (attn + FFN), matching the structure that
-- achieved 2.27 tok/s, but with the matvec body being a proper
-- polyhedral-style Q8_0 kernel (same code as generated by GEMM.hs).
genLayer :: LlamaConfig -> String
genLayer cfg = unlines
  [ "#include <stdint.h>"
  , "#include <math.h>"
  , "#include <string.h>"
  , "#include <omp.h>"
  , ""
  , "typedef struct { uint16_t d; int8_t qs[32]; } block_q8_0;"
  , "static inline float f16_to_f32(uint16_t h) {"
  , "    uint32_t sign = (uint32_t)(h >> 15) << 31;"
  , "    uint32_t exp = (h >> 10) & 0x1F;"
  , "    uint32_t mant = h & 0x3FF;"
  , "    uint32_t f;"
  , "    if (exp == 0) {"
  , "        if (mant == 0) { f = sign; }"
  , "        else { exp = 1; while (!(mant & 0x400)) { mant <<= 1; exp--; }"
  , "               mant &= 0x3FF; f = sign | ((exp + 127 - 15) << 23) | (mant << 13); }"
  , "    } else if (exp == 31) { f = sign | 0x7F800000 | (mant << 13); }"
  , "    else { f = sign | ((exp + 127 - 15) << 23) | (mant << 13); }"
  , "    float r; __builtin_memcpy(&r, &f, 4); return r;"
  , "}"
  , ""
  -- The Q8_0 matvec body — same as polyhedrally generated,
  -- but parameterized as a macro for reuse across projections.
  -- The loop structure matches what the Boulet-Feautrier scanner produces
  -- for the specialized domain {[j,kb] : 0<=j<N, 0<=kb<KB}.
  , "/* Polyhedral Q8_0 matvec: out = W @ x"
  , "   Loop structure: for j in [0,N) { for kb in [0,KB) { dot product } } */"
  , "#define Q8MV_PAR(out, x, W, N, KB) do { \\"
  , "    const block_q8_0* _w = (const block_q8_0*)(W); \\"
  , "    _Pragma(\"omp parallel for schedule(static)\") \\"
  , "    for (int64_t _j = 0; _j < (N); _j++) { \\"
  , "        float _acc = 0.0f; \\"
  , "        for (int64_t _kb = 0; _kb < (KB); _kb++) { \\"
  , "            const block_q8_0* _b = &_w[_j * (KB) + _kb]; \\"
  , "            float _s = f16_to_f32(_b->d); \\"
  , "            float _bs = 0.0f; \\"
  , "            for (int _v = 0; _v < 32; _v++) \\"
  , "                _bs += (x)[_kb*32+_v] * (float)_b->qs[_v]; \\"
  , "            _acc += _s * _bs; \\"
  , "        } \\"
  , "        (out)[_j] = _acc; \\"
  , "    } \\"
  , "} while(0)"
  , ""
  , "#define DIM " ++ show dim
  , "#define KVD " ++ show kvd
  , "#define HID " ++ show hid
  , "#define NH " ++ show nh
  , "#define NKV " ++ show nkv
  , "#define HD " ++ show hd
  , "#define NG " ++ show ng
  , "#define KBD " ++ show kbd
  , "#define KBH " ++ show kbh
  , "#define MAXS " ++ show maxs
  , "#define REPS " ++ show eps ++ "f"
  , ""
  , "static void rmsnorm_serial(float*out, const float*inp, const float*w, int64_t n) {"
  , "    float ss = 0.0f;"
  , "    for (int64_t i = 0; i < n; i++) ss += inp[i]*inp[i];"
  , "    ss = 1.0f / sqrtf(ss/(float)n + REPS);"
  , "    for (int64_t i = 0; i < n; i++) out[i] = inp[i]*ss*w[i];"
  , "}"
  , ""
  , "void fused_layer("
  , "    float*x, float*xb, float*xb2,"
  , "    float*q, float*k, float*v,"
  , "    float*hb, float*hb2,"
  , "    float*attn_out, float*scores,"
  , "    float*kc, float*vc,"
  , "    const void*wq, const void*wk, const void*wv, const void*wo,"
  , "    const void*wg, const void*wu, const void*wd,"
  , "    const float*anw, const float*fnw,"
  , "    const float*inv_freq,"
  , "    int64_t pos"
  , ") {"
  , "    const int64_t sl = pos + 1;"
  , ""
  , "    /* ---- ATTENTION BLOCK ---- */"
  , "    rmsnorm_serial(xb, x, anw, DIM);"
  , ""
  , "    /* Q, K, V projections — each is a polyhedral matvec with its own"
  , "       omp parallel for. The OMP runtime reuses the thread pool. */"
  , "    Q8MV_PAR(q,  xb, wq, DIM, KBD);"
  , "    Q8MV_PAR(k,  xb, wk, KVD, KBD);"
  , "    Q8MV_PAR(v,  xb, wv, KVD, KBD);"
  , ""
  , "    /* RoPE + KV cache update (serial, fast) */"
  , "    for (int64_t h = 0; h < NH; h++) {"
  , "        float*qh = q+h*HD;"
  , "        for (int64_t i = 0; i < HD/2; i++) {"
  , "            float th = (float)pos*inv_freq[i];"
  , "            float co=cosf(th), si=sinf(th);"
  , "            float r0=qh[2*i], r1=qh[2*i+1];"
  , "            qh[2*i]=r0*co-r1*si; qh[2*i+1]=r0*si+r1*co;"
  , "        }"
  , "    }"
  , "    for (int64_t h = 0; h < NKV; h++) {"
  , "        float*kh = k+h*HD;"
  , "        for (int64_t i = 0; i < HD/2; i++) {"
  , "            float th = (float)pos*inv_freq[i];"
  , "            float co=cosf(th), si=sinf(th);"
  , "            float r0=kh[2*i], r1=kh[2*i+1];"
  , "            kh[2*i]=r0*co-r1*si; kh[2*i+1]=r0*si+r1*co;"
  , "        }"
  , "    }"
  , "    memcpy(kc+pos*KVD, k, KVD*sizeof(float));"
  , "    memcpy(vc+pos*KVD, v, KVD*sizeof(float));"
  , ""
  , "    /* Multi-head attention (parallel over Q-heads) */"
  , "    #pragma omp parallel for schedule(static)"
  , "    for (int64_t h = 0; h < NH; h++) {"
  , "        int64_t kvh = h/NG;"
  , "        const float*qh = q+h*HD;"
  , "        float*oh = attn_out+h*HD;"
  , "        float*sc = scores+h*MAXS;"
  , "        float scale = 1.0f/sqrtf((float)HD);"
  , "        for (int64_t t=0;t<sl;t++){"
  , "            float dot=0; const float*kt=kc+t*KVD+kvh*HD;"
  , "            for (int64_t d=0;d<HD;d++) dot+=qh[d]*kt[d];"
  , "            sc[t]=dot*scale;"
  , "        }"
  , "        float mx=sc[0];"
  , "        for (int64_t t=1;t<sl;t++) if(sc[t]>mx)mx=sc[t];"
  , "        float sm=0;"
  , "        for (int64_t t=0;t<sl;t++){sc[t]=expf(sc[t]-mx);sm+=sc[t];}"
  , "        float iv=1.0f/sm;"
  , "        for (int64_t t=0;t<sl;t++)sc[t]*=iv;"
  , "        for (int64_t d=0;d<HD;d++)oh[d]=0;"
  , "        for (int64_t t=0;t<sl;t++){"
  , "            float w=sc[t]; const float*vt=vc+t*KVD+kvh*HD;"
  , "            for (int64_t d=0;d<HD;d++)oh[d]+=w*vt[d];"
  , "        }"
  , "    }"
  , ""
  , "    /* O projection */"
  , "    Q8MV_PAR(xb2, attn_out, wo, DIM, KBD);"
  , "    for (int64_t i=0;i<DIM;i++) x[i]+=xb2[i];"
  , ""
  , "    /* ---- FFN BLOCK ---- */"
  , "    rmsnorm_serial(xb, x, fnw, DIM);"
  , ""
  , "    Q8MV_PAR(hb,  xb, wg, HID, KBD);"
  , "    Q8MV_PAR(hb2, xb, wu, HID, KBD);"
  , ""
  , "    #pragma omp parallel for schedule(static)"
  , "    for (int64_t i=0;i<HID;i++){"
  , "        float g=hb[i]; hb[i]=g/(1.0f+expf(-g))*hb2[i];"
  , "    }"
  , ""
  , "    Q8MV_PAR(xb2, hb, wd, DIM, KBH);"
  , "    for (int64_t i=0;i<DIM;i++) x[i]+=xb2[i];"
  , "}"
  ]
  where
    dim  = lcDim cfg
    kvd  = lcKVDim cfg
    hid  = lcHiddenDim cfg
    nh   = lcNHeads cfg
    nkv  = lcNKVHeads cfg
    hd   = lcHeadDim cfg
    ng   = nh `div` nkv
    kbd  = dim `div` 32
    kbh  = hid `div` 32
    maxs = lcMaxSeqLen cfg
    eps  = lcRMSNormEps cfg
