{-# LANGUAGE BangPatterns #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE ForeignFunctionInterface #-}
{-# LANGUAGE LinearTypes #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE Strict #-}
{-# OPTIONS_GHC -Wno-orphans #-}

-- | Consumable/Dupable/Borrow instances for all ISL owned types.
-- These are expected to be generated by the codegen (at the end of
-- each AutoGen.hs), but the current AutoGen files predate the linear
-- types rewrite. This module provides them manually until the codegen
-- is re-run.
module Isl.Instances () where

import System.IO.Unsafe (unsafePerformIO)
import Unsafe.Coerce (unsafeCoerce)
import Isl.Types

-- Aff
foreign import ccall "isl_aff_free" c_aff_free :: Aff -> IO ()
foreign import ccall "isl_aff_copy" c_aff_copy :: Aff -> IO Aff

instance Consumable Aff where
  consume = unsafeCoerce $ \x -> unsafePerformIO (c_aff_free x)
instance Dupable Aff where
  dup = unsafeCoerce $ \x -> unsafePerformIO $ do
    copy <- c_aff_copy x; return (x, copy)
instance Borrow Aff AffRef where
  borrow = unsafeCoerce $ \(Aff ptr) f -> let !r = f (AffRef ptr) in (r, Aff ptr)

-- Val
foreign import ccall "isl_val_free" c_val_free :: Val -> IO ()
foreign import ccall "isl_val_copy" c_val_copy :: Val -> IO Val

instance Consumable Val where
  consume = unsafeCoerce $ \x -> unsafePerformIO (c_val_free x)
instance Dupable Val where
  dup = unsafeCoerce $ \x -> unsafePerformIO $ do
    copy <- c_val_copy x; return (x, copy)
instance Borrow Val ValRef where
  borrow = unsafeCoerce $ \(Val ptr) f -> let !r = f (ValRef ptr) in (r, Val ptr)

-- Id
foreign import ccall "isl_id_free" c_id_free :: Id -> IO ()
foreign import ccall "isl_id_copy" c_id_copy :: Id -> IO Id

instance Consumable Id where
  consume = unsafeCoerce $ \x -> unsafePerformIO (c_id_free x)
instance Dupable Id where
  dup = unsafeCoerce $ \x -> unsafePerformIO $ do
    copy <- c_id_copy x; return (x, copy)
instance Borrow Id IdRef where
  borrow = unsafeCoerce $ \(Id ptr) f -> let !r = f (IdRef ptr) in (r, Id ptr)

-- BasicSet
foreign import ccall "isl_basic_set_free" c_basic_set_free :: BasicSet -> IO ()
foreign import ccall "isl_basic_set_copy" c_basic_set_copy :: BasicSet -> IO BasicSet

instance Consumable BasicSet where
  consume = unsafeCoerce $ \x -> unsafePerformIO (c_basic_set_free x)
instance Dupable BasicSet where
  dup = unsafeCoerce $ \x -> unsafePerformIO $ do
    copy <- c_basic_set_copy x; return (x, copy)
instance Borrow BasicSet BasicSetRef where
  borrow = unsafeCoerce $ \(BasicSet ptr) f -> let !r = f (BasicSetRef ptr) in (r, BasicSet ptr)

-- Set
foreign import ccall "isl_set_free" c_set_free :: Set -> IO ()
foreign import ccall "isl_set_copy" c_set_copy :: Set -> IO Set

instance Consumable Set where
  consume = unsafeCoerce $ \x -> unsafePerformIO (c_set_free x)
instance Dupable Set where
  dup = unsafeCoerce $ \x -> unsafePerformIO $ do
    copy <- c_set_copy x; return (x, copy)
instance Borrow Set SetRef where
  borrow = unsafeCoerce $ \(Set ptr) f -> let !r = f (SetRef ptr) in (r, Set ptr)

-- UnionSet
foreign import ccall "isl_union_set_free" c_union_set_free :: UnionSet -> IO ()
foreign import ccall "isl_union_set_copy" c_union_set_copy :: UnionSet -> IO UnionSet

instance Consumable UnionSet where
  consume = unsafeCoerce $ \x -> unsafePerformIO (c_union_set_free x)
instance Dupable UnionSet where
  dup = unsafeCoerce $ \x -> unsafePerformIO $ do
    copy <- c_union_set_copy x; return (x, copy)
instance Borrow UnionSet UnionSetRef where
  borrow = unsafeCoerce $ \(UnionSet ptr) f -> let !r = f (UnionSetRef ptr) in (r, UnionSet ptr)

-- BasicMap
foreign import ccall "isl_basic_map_free" c_basic_map_free :: BasicMap -> IO ()
foreign import ccall "isl_basic_map_copy" c_basic_map_copy :: BasicMap -> IO BasicMap

instance Consumable BasicMap where
  consume = unsafeCoerce $ \x -> unsafePerformIO (c_basic_map_free x)
instance Dupable BasicMap where
  dup = unsafeCoerce $ \x -> unsafePerformIO $ do
    copy <- c_basic_map_copy x; return (x, copy)
instance Borrow BasicMap BasicMapRef where
  borrow = unsafeCoerce $ \(BasicMap ptr) f -> let !r = f (BasicMapRef ptr) in (r, BasicMap ptr)

-- Map
foreign import ccall "isl_map_free" c_map_free :: Map -> IO ()
foreign import ccall "isl_map_copy" c_map_copy :: Map -> IO Map

instance Consumable Map where
  consume = unsafeCoerce $ \x -> unsafePerformIO (c_map_free x)
instance Dupable Map where
  dup = unsafeCoerce $ \x -> unsafePerformIO $ do
    copy <- c_map_copy x; return (x, copy)
instance Borrow Map MapRef where
  borrow = unsafeCoerce $ \(Map ptr) f -> let !r = f (MapRef ptr) in (r, Map ptr)

-- UnionMap
foreign import ccall "isl_union_map_free" c_union_map_free :: UnionMap -> IO ()
foreign import ccall "isl_union_map_copy" c_union_map_copy :: UnionMap -> IO UnionMap

instance Consumable UnionMap where
  consume = unsafeCoerce $ \x -> unsafePerformIO (c_union_map_free x)
instance Dupable UnionMap where
  dup = unsafeCoerce $ \x -> unsafePerformIO $ do
    copy <- c_union_map_copy x; return (x, copy)
instance Borrow UnionMap UnionMapRef where
  borrow = unsafeCoerce $ \(UnionMap ptr) f -> let !r = f (UnionMapRef ptr) in (r, UnionMap ptr)

-- Constraint
foreign import ccall "isl_constraint_free" c_constraint_free :: Constraint -> IO ()
foreign import ccall "isl_constraint_copy" c_constraint_copy :: Constraint -> IO Constraint

instance Consumable Constraint where
  consume = unsafeCoerce $ \x -> unsafePerformIO (c_constraint_free x)
instance Dupable Constraint where
  dup = unsafeCoerce $ \x -> unsafePerformIO $ do
    copy <- c_constraint_copy x; return (x, copy)
instance Borrow Constraint ConstraintRef where
  borrow = unsafeCoerce $ \(Constraint ptr) f -> let !r = f (ConstraintRef ptr) in (r, Constraint ptr)

-- Space
foreign import ccall "isl_space_free" c_space_free :: Space -> IO ()
foreign import ccall "isl_space_copy" c_space_copy :: Space -> IO Space

instance Consumable Space where
  consume = unsafeCoerce $ \x -> unsafePerformIO (c_space_free x)
instance Dupable Space where
  dup = unsafeCoerce $ \x -> unsafePerformIO $ do
    copy <- c_space_copy x; return (x, copy)
instance Borrow Space SpaceRef where
  borrow = unsafeCoerce $ \(Space ptr) f -> let !r = f (SpaceRef ptr) in (r, Space ptr)

-- LocalSpace
foreign import ccall "isl_local_space_free" c_local_space_free :: LocalSpace -> IO ()
foreign import ccall "isl_local_space_copy" c_local_space_copy :: LocalSpace -> IO LocalSpace

instance Consumable LocalSpace where
  consume = unsafeCoerce $ \x -> unsafePerformIO (c_local_space_free x)
instance Dupable LocalSpace where
  dup = unsafeCoerce $ \x -> unsafePerformIO $ do
    copy <- c_local_space_copy x; return (x, copy)
instance Borrow LocalSpace LocalSpaceRef where
  borrow = unsafeCoerce $ \(LocalSpace ptr) f -> let !r = f (LocalSpaceRef ptr) in (r, LocalSpace ptr)
